version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=Delfos
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegrafpassword

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - /mnt/c/Users/dudul/Desktop/Delfos/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
